volumes:
  pgstore:                                 # <- Rename "pgstore"
    name: pgstore   

services:
  db:
    container_name: postgres
    image: postgres:12-alpine
    restart: on-failure
    user: postgres
    environment:
      POSTGRES_DB: button-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      PGPORT: 5433
    ports:
      - "5433:5433"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d button-db']
      interval: 5s
      timeout: 5s
    volumes:
      - pgstore:/var/lib/postgresql/data
      - ./src/sql/init.sql:/docker-entrypoint-initdb.d/create_database.sql
  server:
    container_name: server-1
    image: node:18
    restart: always
    env_file: .env.docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 3000