name: CI/CD Pipeline

on:
  push:
    paths:
      - 'dist/**'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        working-directory: ./
        run: npm install

    #   - name: Run linting
    #     working-directory: ./backend
    #     run: npm run lint --if-present

      - name: Build App
        working-directory: ./
        run: npm run build --if-present
          
      - name: Run tests
        working-directory: ./backend
        run: npm run test