name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Install Docker Compose
        run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
        continue-on-error: false

    #   - name: Build Docker image
    #     run: |
    #         docker-compose -f docker-compose.base.yml build

    #   - name: Run Docker image
    #     run: |
    #         docker-compose -f docker-compose.base.yml up -d
            
      - name: ls the curr dir
        run: |
             ls -la

      - name: build dist and run tests
        run: |
             npm install &&
             npm run build &&
             npm run test

    #   - name: Run tests
    #     run: |
    #         docker exec server-1 npm run test