name: CI/CD Pipeline

on:
  push:
    paths:
      - 'dist/**'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prep environment
        run: brew install docker
             colima start
             docker-compose up -d

      - name: Build Docker image
        run: docker-compose -f docker-compose.base.yml build

      - name: Run Docker image
        run: docker-compose -f docker-compose.base.yml up

      - name: Run tests
        run: docker exec server-1 npm run tests